export const SET_APP_STATUS = "app/SET_APP_STATUS";
export const SET_LIGHT_BOX = "app/SET_LIGHT_BOX";
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_CATEGORY = 'SET_CATEGORY';
export const GET_ALL_AFLOGS = 'GET_ALL_AFLOGS';
export const GET_AFLOGS_BY_CATEGORY = 'GET_AFLOGS_BY_CATEGORY';
export const CLEAR_AFLOGS = 'CLEAR_AFLOGS';

// authenticate
export const LOGOUT = 'LOGOUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const APPLY_COLLABORATE_SUCCESS = 'APPLY_COLLABORATE_SUCCESS';
export const APPLY_CHECK_SUCCESS = 'APPLY_CHECK_SUCCESS';

